config/routes.rb
Rails.application.routes.draw do

  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    resources :items, only: [:new,:create,:index,:show,:edit,:update]
    resources :genres, only: [:index, :create, :edit, :update]
  end

  scope module: :public do
    resources :items ,only: [:index,:show]
      resources :cart_items ,only: [:index,:create,:update,:destroy] do
        collection do
          delete 'all_destroy'
        end
      end
    post "/orders/log"=> "orders#log",as:"log"
    resources :orders, only: [:new]
    get "/about" => "homes#about", as: "about"
    root to: "homes#top"
  end
end

app/models/address.rb
class Address < ApplicationRecord
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
   belongs_to :item
   belongs_to :customer

 def with_tax_price
    (price * 1.1).floor
 end


  def subtotal
      item.with_tax_price * item_count
  end

def sum_price
    item.with_tax_price*item_count
end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :addresses, dependent: :destroy
  has_many :cart_items
  has_many :orders

end

app/models/genre.rb
class Genre < ApplicationRecord
   has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :genre
  has_one_attached :item_image
  has_many :cart_items


  def get_item_image(width, height)
    unless item_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      item_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpg')
    end
    item_image.variant(resize_to_limit: [width, height]).processed
  end

 def with_tax_price
    (price * 1.1).floor
 end

  def subtotal
      item.with_tax_price * amount
  end

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer

  enum payment_method: { "クレジットカード": 0, "銀行振込": 1 }
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
    belongs_to :order
    belongs_to :item


  def subtotal
    item.with_tax_price * item_count
  end
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController

  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to admin_genres_path
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      redirect_to admin_genres_path
    end
  end



  private
  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

  def new
    @item = Item.new
    @genres = Genre.all
  end

  def index
    @itemes = Item.all
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
    @genres = Genre.all
  end

  def update
    @item = Item.find(params[:id])
    @item.update(iteme_params)
    redirect_to root_path
  end

  def create
    @item = Item.new(iteme_params)
    @item.save
    redirect_to root_path
  end

  private
  def iteme_params
    params.require(:item).permit(:item_image,:name,:introduction,:genre_id,:price)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
end

app/controllers/admin/passwords_controller.rb
# frozen_string_literal: true

class Admin::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/genres/edit.html.erb
<h1>ジャンルの編集ページ</h1>
<%= form_with model: @genre, url:admin_genre_path do |f| %>
  <p><%= f.label :name, "ジャンル名" %></p>
  <p><%= f.text_field :name %></p>
  <p><%= f.submit "変更を保存" %></p>
<%end%>

app/views/admin/genres/index.html.erb
<h1>ジャンル一覧ページ</h1>

<%=form_with model: @genre, url:admin_genres_path do |f| %>
  <%=f.label :name, "ジャンル名" %>
  <%=f.text_field :name %>
  <%= f.submit "新規登録" %>
<%end%>

<% @genres.each do |genre| %>
  <p><%= genre.name%></p>
  <%= link_to "編集する", edit_admin_genre_path(genre) %>
<%end%>

app/views/admin/items/edit.html.erb
<h1>商品編集ページ</h1>
<%= form_with model: @item, url:admin_item_path(@item), method: :patch do |f| %>

  <%= f.label :item_image, "商品画像", class: "col-sm-3" %>
  <%= f.file_field :item_image, accept: 'image/*' %>
<br>
<br>
  <%= f.label :name, "商品名" %>
  <%= f.text_field :name %>
<br>
<br>
  <%= f.label :introduction, "商品説明"%>
  <%= f.text_area :introduction, placeholder: "ここに説明文を記述します" %>
<br>
<br>
  <%= f.label :genre_id, "ジャンル"%>
  <%= f.collection_select :genre_id, @genres, :id, :name, {include_blank: "--選択してください--"}%>
<br>
<br>
 <%= f.label :price, "税抜価格"%>
  <%= f.text_field :price, placeholder: "1000" %> 円
<br>
<br>
  <%= f.submit "変更" %>
<% end %>

app/views/admin/items/index.html.erb
<h1>全ての商品一覧</h1>
<% @itemes.each do |item| %>
     <%= link_to admin_item_path(item.id) do %>
     <%= image_tag item.get_item_image(150,150) %>
    <% end %>
    <%= item.name %><br>
    <%= item.price %>
<%end%>

app/views/admin/items/new.html.erb
<h1>商品新規登録</h1>

<%= form_with model: @item, url:admin_items_path do |f| %>
<%= f.label :item_image , "商品画像" %>
<%= f.file_field :item_image%>
<br>
<br>
  <%= f.label :name, "商品名" %>
  <%= f.text_field :name, placeholder: "商品名" %>
<br>
<br>
  <%= f.label :introduction,"商品説明" %>
  <%= f.text_field :introduction, placeholder: "商品の説明を書く" %>
<br>
<br>
  <%= f.label :genre_id, "ジャンル", class: "col-sm-3" %>
  <%= f.collection_select :genre_id, @genres, :id, :name, {include_blank: "--選択してください--"} %>
<br>
<br>
 <%= f.label :price, "税抜価格" %>
 <%= f.text_field :price, placeholder: "1000" %>
<br>
<br>
<%= f.label :is_active, "販売ステータス" %>
<%= f.radio_button :is_active, :true %>
<%= f.label :is_active, "販売中", value: :true%>
<%= f.radio_button :is_active, :false %>
<%= f.label :is_active, "販売停止中", value: :false %>
<br>
<br>
  <%=f.submit "新規登録" %>
<%end%>

app/views/admin/items/show.html.erb
<h1>商品の詳細ページ</h1>

<h2>商品の名前</h2>
<%=@item.name %>
<h2>商品の値段</h2>
<%=@item.price %>
<h2>商品画像</h2>
<%= image_tag @item.get_item_image(150,150) %>

<br>
<br>
<%=link_to "編集する", edit_admin_item_path %>